# ======== SERVER ========
server.port=8080

# ======== H2 (développement) ========
spring.datasource.url=jdbc:h2:mem:mmidb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ======== JPA ========
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ======== JWT ========
app.jwt.secret=mmiSecretKey2025SuperLongKeyForHMACAlgorithmAtLeast256Bits
app.jwt.expiration=86400000

# ======== MAIL (configurer avec vos vraies valeurs) ========
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=projettutore77100@gmail.com
spring.mail.password=oelqapbehouiafqw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Email admin pour les notifications
app.admin.email=projettutore77100@gmail.com
